name: SSHX Beast Mode (128GB RAM / 1.2TB Storage)

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 */5 * * *'  # Restart every 5 hours

jobs:
  terminal:
    runs-on: ubuntu-latest  # Boom—upgraded! (Confirm label in your settings)
    timeout-minutes: 350  # Still under 6hr cap
    steps:
    - uses: actions/checkout@v4

    - name: Install Base Deps
      run: |
        sudo apt update
        sudo apt install -y curl build-essential  # Scale for big builds

    - name: Download & Launch SSHX v0.4.1
      run: |
        curl -sSf https://sshx.io/get | sh -s run
        chmod +x sshx
        ./sshx --session-name "beast-vps-$(date +%s)" &
        sleep 15
        SESSION_URL=
        echo "🔗 Mega terminal at: $SESSION_URL"
        echo "SESSION_URL=$SESSION_URL" >> $GITHUB_ENV

    - name: Keeper & Beefy Backup
      run: |
        while true; do
          echo "Heartbeat: $(date)" >> heartbeat.log
          # Backup more aggressively—1.2TB gives room
          TIMESTAMP=$(date +%s)
          tar -czf "backup-$TIMESTAMP.tar.gz" . --exclude='*.git' --exclude='__pycache__'
          # Upload to release for persistence across runs
          gh release create "backup-$TIMESTAMP" --title "Beast Save $TIMESTAMP" "backup-$TIMESTAMP.tar.gz" || true
          sleep 300
        done
