name: SSHX Terminal VPS

on:
  workflow_dispatch:  # Manual start
  schedule:
    - cron: '0 */5 * * *'  # Auto-restart every 5 hours (under 6hr cap)

jobs:
  terminal:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # ~5.8 hours max
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y curl build-essential  # For Rust if needed

    - name: Download & Run SSHX
      run: |
        # Grab latest sshx binary (check sshx.io for updates)
        curl -L https://github.com/ekzhang/sshx/releases/latest/download/sshx-x86_64-unknown-linux-gnu -o sshx
        chmod +x sshx
        ./sshx --session-name "my-vps-$(date +%s)" &  # Background it
        # Wait for it to boot
        sleep 10
        # Print the share link (logs will show it)
        echo "Access your terminal at: $(./sshx --list | grep -o 'https://sshx.io/s/[a-zA-Z0-9]*')"  # Tweak if needed

    - name: Keep Alive & Backup Hook
      run: |
        # Infinite loop to hold session
        while true; do
          echo "Session alive at $(date)" >> session.log
          # Quick backup: Tar key dirs & push to repo (or upload to GitHub release)
          tar -czf backup-$(date +%s).tar.gz ~/workflows/  # Your files in workspace
          # Optional: gh release create backup-$(date +%s) --title "Auto Backup" backup-*.tar.gz
          sleep 300  # Check every 5 mins
        done
